更新 build-apk-rustdesk.yml

diff --git a/.github/workflows/build-apk-rustdesk.yml b/.github/workflows/build-apk-rustdesk.yml
--- a/.github/workflows/build-apk-rustdesk.yml
+++ b/.github/workflows/build-apk-rustdesk.yml
@@ -7,8 +7,8 @@ on:
 env:
   JDK_VERSION: '17'
   JDK_DISTRIBUTION: 'temurin'
-  ANDROID_COMPILE_SDK: '35'
-  ANDROID_BUILD_TOOLS: '35.0.0'
+  # ANDROID_COMPILE_SDK: '35'
+  # ANDROID_BUILD_TOOLS: '35.0.0'
   RUST_VERSION: '1.75'
   CARGO_NDK_VERSION: '3.1.2'
   NDK_VERSION: 'r28c'
@@ -47,21 +47,21 @@ jobs:
         run: |
           echo "BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
 
-      - name: Update android sdk version
-        working-directory: ./rustdesk_source/flutter
-        run: |
-          sed -i -E 's/compileSdk(Version)?[[:space:]]*[=]?[[:space:]]*34/compileSdk = 35/g' android/app/build.gradle
-          echo "✅ Updated compileSdk:"
-          grep -C2 "compileSdk" android/app/build.gradle || echo "⚠️  Could not verify, please check manually."
+      # - name: Update android sdk version
+      #   working-directory: ./rustdesk_source/flutter
+      #   run: |
+      #     sed -i -E 's/compileSdk(Version)?[[:space:]]*[=]?[[:space:]]*34/compileSdk = 35/g' android/app/build.gradle
+      #     echo "✅ Updated compileSdk:"
+      #     grep -C2 "compileSdk" android/app/build.gradle || echo "⚠️  Could not verify, please check manually."
 
-      - name: Install android sdk components
-        run: |
-          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
-          rm -rf /usr/local/lib/android/sdk/platforms/android-${{ env.ANDROID_COMPILE_SDK }}
-          yes | sdkmanager --licenses > /dev/null || true
-          sdkmanager "platforms;android-${{ env.ANDROID_COMPILE_SDK }}" "build-tools;${{ env.ANDROID_BUILD_TOOLS }}"
-          echo "Installed platforms:"
-          ls -la /usr/local/lib/android/sdk/platforms/
+      # - name: Install android sdk components
+      #   run: |
+      #     export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
+      #     rm -rf /usr/local/lib/android/sdk/platforms/android-${{ env.ANDROID_COMPILE_SDK }}
+      #     yes | sdkmanager --licenses > /dev/null || true
+      #     sdkmanager "platforms;android-${{ env.ANDROID_COMPILE_SDK }}" "build-tools;${{ env.ANDROID_BUILD_TOOLS }}"
+      #     echo "Installed platforms:"
+      #     ls -la /usr/local/lib/android/sdk/platforms/
 
       - name: Setup java
         uses: actions/setup-java@main
