更新 build-apk-bilipai.yml

diff --git a/.github/workflows/build-apk-bilipai.yml b/.github/workflows/build-apk-bilipai.yml
--- a/.github/workflows/build-apk-bilipai.yml
+++ b/.github/workflows/build-apk-bilipai.yml
@@ -1,19 +1,19 @@
 name: build-apk-bilipai
- 
+
 on:
   workflow_dispatch:
   workflow_call:
- 
+
 env:
   JDK_VERSION: '21'
   JDK_DISTRIBUTION: 'temurin'
   ANDROID_COMPILE_SDK: '36'
   ANDROID_BUILD_TOOLS: '36.0.0'
   GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
- 
+
 permissions:
   contents: write
- 
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -33,12 +33,12 @@ jobs:
           path: bilipai_source
           fetch-depth: 0
           submodules: false
- 
+
       - name: Checkout ci source repo
         uses: actions/checkout@main
         with:
           path: ci_source
- 
+
       - name: Generate timestamp
         run: |
           echo "BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
@@ -48,7 +48,7 @@ jobs:
         with:
           java-version: "${{ env.JDK_VERSION }}"
           distribution: "${{ env.JDK_DISTRIBUTION }}"
- 
+
       - name: Decode keystore and create init script
         working-directory: ./bilipai_source
         run: |
@@ -74,6 +74,17 @@ jobs:
               }
           }
           EOF
+ 
+      - name: Disable onboarding screen
+        working-directory: ./bilipai_source
+        run: |
+          APPNAVIGATIONFILE="app/src/main/java/com/android/purebilibili/navigation/AppNavigation.kt"
+          sed -i 's/^[[:space:]]*val startDestination = if (firstLaunchShown) ScreenRoutes.Home\.route else ScreenRoutes\.Onboarding\.route/val startDestination = ScreenRoutes.Home.route/' "$APPNAVIGATIONFILE"
+          if grep -q 'val startDestination = ScreenRoutes\.Home\.route' "$APPNAVIGATIONFILE"; then
+            echo "✅ Onboarding screen disabled successfully."
+          else
+            echo "❌ Failed to disable onboarding screen." && exit 1
+          fi
  
       - name: Build signed apk with init script
         working-directory: ./bilipai_source
